# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1V7NC-pV3SNiM3RD5gKO3SuSkyVhzsZsR
"""

def calculator():
    print("Simple Calculator")
    print("Operations: +, -, *, /")

    while True:
        try:
            num1 = float(input("\nEnter the first number: "))
            operator = input("Enter an operator (+, -, *, /): ")
            num2 = float(input("Enter the second number: "))

            if operator == "+":
                result = num1 + num2
            elif operator == "-":
                result = num1 - num2
            elif operator == "*":
                result = num1 * num2
            elif operator == "/":
                if num2 != 0:
                    result = num1 / num2
                else:
                    print("Error: Division by zero is not allowed.")
                    continue
            else:
                print("Error: Invalid operator.")
                continue

            print(f"Result: {result}")
        except ValueError:
            print("Error: Please enter valid numbers.")

        again = input("Do you want to perform another calculation? (yes/no): ").lower()
        if again != "yes":
            print("Goodbye!")
            break

calculator()